### ISSUE TITLE
Spaceship map

### ISSUE THREAD

**Issue by technomancy** [technomancy/calandria#14]
So far I've got a cargo bay, engineering section with reactor, an engine, a mess hall, and mesecons conduits bringing power from the reactor to various systems, an elevator, and a lab: http://p.hagelb.org/calandria-ship.tar.gz

It would be cool to create a map with a lot of puzzles you have to write programs to solve; see the readme for detailed ideas.

**Comment by kilbith** [comment]
What about the USS Enterprise ?

Download link : https://forum.minetest.net/download/file.php?id=1204
Tutorial for import it : https://forum.minetest.net/viewtopic.php?f=12&t=9400

![abtwa2w](https://cloud.githubusercontent.com/assets/7883281/7881979/2f1aae94-0609-11e5-8ff9-92a6403b5ba3.png)

**Comment by technomancy** [comment]
Pretty cool, but it would be difficult to add all the functionality I need to an existing model. I think the model needs to grow out of the gameplay requirements; form following function.

**Comment by technomancy** [comment]
Should track this separately in the ss-calandria repo.
