### ISSUE TITLE
Investigate pipeworks

### ISSUE THREAD

**Issue by technomancy** [technomancy/calandria#3]
Could do cool things with pumping fuel or coolant to the engine.

**Comment by technomancy** [comment]
This isn't really part of this mod.

**Comment by asl97** [comment]
the item logic in pipeworks isn't that bad but the liquid logic is just not as good.

the liquid logic for the pipe just check for a `loaded` liquid pipe and the water source and add the water source pos to itself in the meta

while the spigot and fountainhead just check for any node with the `_loaded` in the name ( https://github.com/VanessaE/pipeworks/issues/114 )

---

it's more or less the same with technic, the switching station does everything, there is no flow logic at all.

---

what would be cool is a pipe mod that can really do flowing liquid like those for minecraft (buildcraft mod) shown in youtube video. (and maybe power flow as well)
